##### Load required packages

In [7]:
import scipy.io as sio
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from cmath import nan
from sklearn.metrics import confusion_matrix

##### Load data

In [ ]:
'''
def load_data():
    mat_load = sio.loadmat('C:/Users/Zephyrus/Desktop/data/allTraces.mat')['allTraces']
    roi_load = sio.loadmat('C:/Users/Zephyrus/Desktop/data/allROIPositions.mat')['allROIPositions']
    ind_load = sio.loadmat('C:/Users/Zephyrus/Desktop/data/blFinalHit.mat')['blFinalHit']
    list1 = sio.loadmat('C:/Users/Zephyrus/Desktop/data/indicesSession1.mat')['indSess1']
    list2 = sio.loadmat('C:/Users/Zephyrus/Desktop/data/List2.mat')['List2']
    list3 = sio.loadmat('C:/Users/Zephyrus/Desktop/data/List3.mat')['List3']
    list4 = sio.loadmat('C:/Users/Zephyrus/Desktop/data/List4.mat')['List4']
    return mat_load, roi_load, ind_load, list1, list2, list3, list4
''' 

In [8]:
def load_data():
    mat_load = sio.loadmat('C:/Users/m.nedeljkovic/Desktop/data/allTraces.mat')['allTraces']
    roi_load = sio.loadmat('C:/Users/m.nedeljkovic/Desktop/data/allROIPositions.mat')['allROIPositions']
    ind_load = sio.loadmat('C:/Users/m.nedeljkovic/Desktop/data/blFinalHit.mat')['blFinalHit']
    list1 = sio.loadmat('C:/Users/m.nedeljkovic/Desktop/data/indicesSession1.mat')['indSess1']
    list2 = sio.loadmat('C:/Users/m.nedeljkovic/Desktop/data/List2.mat')['List2']
    list3 = sio.loadmat('C:/Users/m.nedeljkovic/Desktop/data/List3.mat')['List3']
    list4 = sio.loadmat('C:/Users/m.nedeljkovic/Desktop/data/List4.mat')['List4']
    return mat_load, roi_load, ind_load, list1, list2, list3, list4

## Data preparation for the CNN models

- 1 region, all info about speakers, 4 sessions, white noise, 50 info per neuron (per speaker), 100 neurons per region => image 100x250(5x50) - 8 of them (2 states x 4 sessions) x 30 (sampling points over time)
- final 240 images (120 per state)
- oversampling input images with NaNs (maybe random oversampling)
- representing input images as different stimulus (100 x 50)
- combination of 2 different regions in one image / mice????
- including bandpass noise into data representation 
- representing input images as different stimulus (100 x 50)

### 1. One image - all regions, all speakers, neurons (oversampling with NaNs) - 100x60 (400)
- approx 100 neurons per region x 60 (5 speakers x 12 regions)
- 50 values x 4 sessions x 2 states -> 200 images per state

In [123]:
#lenghts of each trial
from cmath import isinf

def data_per_trial(tr, mat_load, roi_load, ind_load, list1, list2, list3, list4):
    lista = [[k[0] for k in list1], [k[0] for k in list2], [k[0] for k in list3], [k[0] for k in list4]]
    index = [0, 118, 88, 100, 98, 109, 78, 121, 76, 113, 97, 112, 118]

    for trial in range(1,len(index)):
        
        index[trial] = index[trial] + index[trial-1]
        dat_tr = mat_load[index[trial-1] : index[trial]+1, :, :, 0, :, :, :]
        ind_tr = ind_load[index[trial-1] : index[trial]+1, :, :, 0, :, :]

        #choose state
        dat_stan = dat_tr[:, 0, :, :, :, :]
        dat_staw = dat_tr[:, 1, :, :, :, :]
        ind_stan = ind_tr[:, 0, :, :, :]
        ind_staw = ind_tr[:, 1, :, :, :]

        br = 1

        if(trial == tr):
            for sesion in range(4):
                
                lista_ = lista[sesion]
                #choose session
                dat_sean = dat_stan[:, sesion, :, :, :]
                dat_seaw = dat_staw[:, sesion, :, :, :]
                ind_sean = ind_stan[:, sesion, :, :]
                ind_seaw = ind_staw[:, sesion, :, :]

                for sample in range(50):

                    dat_sean_df = dat_sean[:, :, sample, :]
                    dat_seaw_df = dat_seaw[:, :, sample, :]
                    ind_sean_df = ind_sean[:, :, sample]
                    ind_seaw_df = ind_seaw[:, :, sample]
                    ind_sean_df = ind_sean_df.astype('float')
                    ind_seaw_df = ind_seaw_df.astype('float')
                    ind_sean_df[ind_sean_df == 0] = 'nan' 
                    ind_seaw_df[ind_seaw_df == 0] = 'nan' 

                    dat_sean_df_ = dat_sean_df[0:1,:,:]
                    dat_seaw_df_ = dat_seaw_df[0:1,:,:]
                    ind_sean_df_ = ind_sean_df[0:1,:]
                    ind_seaw_df_ = ind_seaw_df[0:1,:]
                    for matrix in range(0,np.shape(dat_sean_df)[0]-1):
                        if(index[trial-1]+matrix in lista_):
                            dat_sean_df_ = np.append(dat_sean_df_, dat_sean[matrix][:, sample, :].reshape(1,dat_sean[matrix][:, sample, :].shape[0],dat_sean[matrix][:, sample, :].shape[1]), axis=0)
                            dat_seaw_df_ = np.append(dat_seaw_df_, dat_seaw[matrix][:, sample, :].reshape(1,dat_seaw[matrix][:, sample, :].shape[0],dat_seaw[matrix][:, sample, :].shape[1]), axis=0)
                            ind_sean_df_ = np.append(ind_sean_df_, ind_sean[matrix][:, sample].reshape(1, ind_sean[matrix][:, sample].shape[0]), axis=0)
                            ind_seaw_df_ = np.append(ind_seaw_df_, ind_seaw[matrix][:, sample].reshape(1, ind_seaw[matrix][:, sample].shape[0]), axis=0)
                    dat_sean_df = dat_sean_df_[1:,:,:]
                    dat_seaw_df = dat_seaw_df_[1:,:,:]
                    ind_sean_df = ind_sean_df_[1:,:]
                    ind_seaw_df = ind_seaw_df_[1:,:]
                
                    for time in range(31):
                        dat_sean_df[:,:,time] = np.multiply(np.array(dat_sean_df[:,:,time]),ind_sean_df)
                        dat_seaw_df[:,:,time] = np.multiply(np.array(dat_seaw_df[:,:,time]),ind_seaw_df)
                            
                    dat_sean_df = dat_sean_df.reshape(dat_sean_df.shape[0],155)
                    dat_seaw_df = dat_seaw_df.reshape(dat_seaw_df.shape[0],155)
                    dat_sean_df[dat_sean_df == np.inf] = 0
                    dat_seaw_df[dat_seaw_df == np.inf] = 0
                    if(np.any(dat_seaw_df == np.inf)==True or np.any(dat_sean_df == np.inf)==True or np.any(dat_sean_df == -np.inf)==True or np.any(dat_seaw_df == -np.inf)==True):
                        print(1)

                    file1 = "C:/Users/m.nedeljkovic/Desktop/cnn data/data/an" + str(br) + ".npy"
                    file2 = "C:/Users/m.nedeljkovic/Desktop/cnn data/data/aw" + str(br) + ".npy"
                    #file1 = "C:/Users/Zephyrus/Desktop/cnn data/data/an" + str(br) + ".npy"
                    #file2 = "C:/Users/Zephyrus/Desktop/cnn data/data/aw" + str(br) + ".npy"
                    
                    np.save(file1, dat_sean_df)
                    np.save(file2, dat_seaw_df)
                    br = br + 1
            

In [124]:
mat_load, roi_load, ind_load, list1, list2, list3, list4 = load_data()
data_per_trial(1, mat_load, roi_load, ind_load, list1, list2, list3, list4)

C:\Users\m.nedeljkovic\AppData\Local\Temp\ipykernel_10432\3636843975.py:60: RuntimeWarning: invalid value encountered in multiply
  dat_seaw_df[:,:,time] = np.multiply(np.array(dat_seaw_df[:,:,time]),ind_seaw_df)


### 2. One region -  training on one session, evaluation on different 

In [127]:
#lenghts of each trial
from cmath import isinf

def data_per_ses(tr, ses, mat_load, roi_load, ind_load, list1, list2, list3, list4):
    lista = [[k[0] for k in list1], [k[0] for k in list2], [k[0] for k in list3], [k[0] for k in list4]]
    index = [0, 118, 88, 100, 98, 109, 78, 121, 76, 113, 97, 112, 118]

    for trial in range(1,len(index)):
        
        index[trial] = index[trial] + index[trial-1]
        dat_tr = mat_load[index[trial-1] : index[trial]+1, :, :, 0, :, :, :]
        ind_tr = ind_load[index[trial-1] : index[trial]+1, :, :, 0, :, :]

        #choose state
        dat_stan = dat_tr[:, 0, :, :, :, :]
        dat_staw = dat_tr[:, 1, :, :, :, :]
        ind_stan = ind_tr[:, 0, :, :, :]
        ind_staw = ind_tr[:, 1, :, :, :]

        br = 1

        if(trial == tr):
            for sesion in range(4):
                
                if(sesion ==  ses):

                    lista_ = lista[sesion]
                    #choose session
                    dat_sean = dat_stan[:, sesion, :, :, :]
                    dat_seaw = dat_staw[:, sesion, :, :, :]
                    ind_sean = ind_stan[:, sesion, :, :]
                    ind_seaw = ind_staw[:, sesion, :, :]

                    for sample in range(50):

                        dat_sean_df = dat_sean[:, :, sample, :]
                        dat_seaw_df = dat_seaw[:, :, sample, :]
                        ind_sean_df = ind_sean[:, :, sample]
                        ind_seaw_df = ind_seaw[:, :, sample]
                        ind_sean_df = ind_sean_df.astype('float')
                        ind_seaw_df = ind_seaw_df.astype('float')
                        ind_sean_df[ind_sean_df == 0] = 'nan' 
                        ind_seaw_df[ind_seaw_df == 0] = 'nan' 

                        dat_sean_df_ = dat_sean_df[0:1,:,:]
                        dat_seaw_df_ = dat_seaw_df[0:1,:,:]
                        ind_sean_df_ = ind_sean_df[0:1,:]
                        ind_seaw_df_ = ind_seaw_df[0:1,:]
                        for matrix in range(0,np.shape(dat_sean_df)[0]-1):
                            if(index[trial-1]+matrix in lista_):
                                dat_sean_df_ = np.append(dat_sean_df_, dat_sean[matrix][:, sample, :].reshape(1,dat_sean[matrix][:, sample, :].shape[0],dat_sean[matrix][:, sample, :].shape[1]), axis=0)
                                dat_seaw_df_ = np.append(dat_seaw_df_, dat_seaw[matrix][:, sample, :].reshape(1,dat_seaw[matrix][:, sample, :].shape[0],dat_seaw[matrix][:, sample, :].shape[1]), axis=0)
                                ind_sean_df_ = np.append(ind_sean_df_, ind_sean[matrix][:, sample].reshape(1, ind_sean[matrix][:, sample].shape[0]), axis=0)
                                ind_seaw_df_ = np.append(ind_seaw_df_, ind_seaw[matrix][:, sample].reshape(1, ind_seaw[matrix][:, sample].shape[0]), axis=0)
                        dat_sean_df = dat_sean_df_[1:,:,:]
                        dat_seaw_df = dat_seaw_df_[1:,:,:]
                        ind_sean_df = ind_sean_df_[1:,:]
                        ind_seaw_df = ind_seaw_df_[1:,:]
                    
                        for time in range(31):
                            dat_sean_df[:,:,time] = np.multiply(np.array(dat_sean_df[:,:,time]),ind_sean_df)
                            dat_seaw_df[:,:,time] = np.multiply(np.array(dat_seaw_df[:,:,time]),ind_seaw_df)
                                
                        dat_sean_df = dat_sean_df.reshape(dat_sean_df.shape[0],155)
                        dat_seaw_df = dat_seaw_df.reshape(dat_seaw_df.shape[0],155)
                        dat_sean_df[dat_sean_df == np.inf] = 0
                        dat_seaw_df[dat_seaw_df == np.inf] = 0
                        if(np.any(dat_seaw_df == np.inf)==True or np.any(dat_sean_df == np.inf)==True or np.any(dat_sean_df == -np.inf)==True or np.any(dat_seaw_df == -np.inf)==True):
                            print(1)
                
                        file1 = "C:/Users/m.nedeljkovic/Desktop/cnn data/data/an" + str(br) + ".npy"
                        file2 = "C:/Users/m.nedeljkovic/Desktop/cnn data/data/aw" + str(br) + ".npy"
                        #file1 = "C:/Users/Zephyrus/Desktop/cnn data/data/an" + str(br) + ".npy"
                        #file2 = "C:/Users/Zephyrus/Desktop/cnn data/data/aw" + str(br) + ".npy"
                        print(dat_sean_df)
                        np.save(file1, dat_sean_df)
                        np.save(file2, dat_seaw_df)
                        br = br + 1
       


In [128]:
mat_load, roi_load, ind_load, list1, list2, list3, list4 = load_data()
data_per_ses(1, 0, mat_load, roi_load, ind_load, list1, list2, list3, list4)

[[0.33109264 0.32496383 0.29860054 ... 0.         0.         0.        ]
 [0.28019113 0.2704302  0.24499258 ... 0.27654195 0.26300647 0.25435275]
 [0.2575461  0.25465754 0.2548965  ... 0.27127423 0.26166307 0.25892291]
 ...
 [       nan        nan        nan ...        nan        nan        nan]
 [0.268755   0.25704964 0.27359293 ... 0.28662127 0.29536471 0.25557347]
 [0.3620192  0.36264946 0.39781699 ... 0.39719208 0.44058525 0.42091839]]
[[0.         0.         0.         ... 0.19553343 0.19791905 0.20625539]
 [0.25375484 0.2268333  0.25719615 ... 0.23555272 0.24336095 0.22763782]
 [0.23833666 0.23352802 0.24599235 ... 0.24926321 0.2599069  0.24835725]
 ...
 [       nan        nan        nan ...        nan        nan        nan]
 [0.25586238 0.26398835 0.27593638 ... 0.2637159  0.23233325 0.29181527]
 [0.3750598  0.39063895 0.36775345 ... 0.28875335 0.30835825 0.32146574]]
[[0.19579912 0.19509603 0.19183389 ... 0.         0.         0.        ]
 [0.24832089 0.24521927 0.26080673 ... 

C:\Users\m.nedeljkovic\AppData\Local\Temp\ipykernel_10432\3558967917.py:62: RuntimeWarning: invalid value encountered in multiply
  dat_seaw_df[:,:,time] = np.multiply(np.array(dat_seaw_df[:,:,time]),ind_seaw_df)


[[0.18223643 0.18737237 0.18122259 ... 0.17957785 0.19372254 0.190817  ]
 [0.28034708 0.27645806 0.3072522  ... 0.28681195 0.28917319 0.29996282]
 [0.2684249  0.28264314 0.25849214 ... 0.2837252  0.27276176 0.27426832]
 ...
 [       nan        nan        nan ...        nan        nan        nan]
 [0.28232093 0.23222147 0.24651943 ... 0.28332685 0.26190894 0.27266186]
 [0.25344963 0.25982068 0.25846853 ... 0.28266305 0.27970026 0.29674147]]
[[0.         0.         0.         ... 0.18605    0.23159183 0.28405895]
 [0.28968753 0.29951615 0.26767236 ... 0.28897434 0.28561202 0.28278966]
 [0.28206862 0.29833894 0.2833539  ... 0.27782557 0.27805349 0.2801662 ]
 ...
 [       nan        nan        nan ...        nan        nan        nan]
 [0.         0.         0.         ... 0.27820951 0.28208141 0.28304288]
 [0.27666117 0.26260094 0.2738888  ... 0.28853591 0.29244072 0.29641971]]
[[0.2091178  0.2383439  0.23871846 ... 0.         0.         0.        ]
 [0.2806263  0.30012931 0.30288777 ... 

### 3. One region - classification on different speakers

In [121]:
#lenghts of each trial
from cmath import isinf

def data_speak(tr, mat_load, roi_load, ind_load, list1, list2, list3, list4):
    lista = [[k[0] for k in list1], [k[0] for k in list2], [k[0] for k in list3], [k[0] for k in list4]]
    index = [0, 118, 88, 100, 98, 109, 78, 121, 76, 113, 97, 112, 118]

    for trial in range(1,len(index)):
        
        index[trial] = index[trial] + index[trial-1]
        dat_tr = mat_load[index[trial-1] : index[trial]+1, :, :, 0, :, :, :]
        ind_tr = ind_load[index[trial-1] : index[trial]+1, :, :, 0, :, :]

        #choose state
        dat_stan = dat_tr[:, 0, :, :, :, :]
        dat_staw = dat_tr[:, 1, :, :, :, :]
        ind_stan = ind_tr[:, 0, :, :, :]
        ind_staw = ind_tr[:, 1, :, :, :]

        br = 1

        if(trial == tr):
            for sesion in range(4):
                
                lista_ = lista[sesion]
                #choose session
                dat_sean = dat_stan[:, sesion, :, :, :]
                dat_seaw = dat_staw[:, sesion, :, :, :]
                ind_sean = ind_stan[:, sesion, :, :]
                ind_seaw = ind_staw[:, sesion, :, :]

                for sample in range(50):

                    dat_sean_df = dat_sean[:, :, sample, :]
                    dat_seaw_df = dat_seaw[:, :, sample, :]
                    ind_sean_df = ind_sean[:, :, sample]
                    ind_seaw_df = ind_seaw[:, :, sample]
                    ind_sean_df = ind_sean_df.astype('float')
                    ind_seaw_df = ind_seaw_df.astype('float')
                    ind_sean_df[ind_sean_df == 0] = 'nan' 
                    ind_seaw_df[ind_seaw_df == 0] = 'nan' 

                    dat_sean_df_ = dat_sean_df[0:1,:,:]
                    dat_seaw_df_ = dat_seaw_df[0:1,:,:]
                    ind_sean_df_ = ind_sean_df[0:1,:]
                    ind_seaw_df_ = ind_seaw_df[0:1,:]
                
                    for matrix in range(0,np.shape(dat_sean_df)[0]-1):
                        if(index[trial-1]+matrix in lista_):
                            dat_sean_df_ = np.append(dat_sean_df_, dat_sean[matrix][:, sample, :].reshape(1,dat_sean[matrix][:, sample, :].shape[0],dat_sean[matrix][:, sample, :].shape[1]), axis=0)
                            dat_seaw_df_ = np.append(dat_seaw_df_, dat_seaw[matrix][:, sample, :].reshape(1,dat_seaw[matrix][:, sample, :].shape[0],dat_seaw[matrix][:, sample, :].shape[1]), axis=0)
                            ind_sean_df_ = np.append(ind_sean_df_, ind_sean[matrix][:, sample].reshape(1, ind_sean[matrix][:, sample].shape[0]), axis=0)
                            ind_seaw_df_ = np.append(ind_seaw_df_, ind_seaw[matrix][:, sample].reshape(1, ind_seaw[matrix][:, sample].shape[0]), axis=0)

                    dat_sean_dfn = dat_sean_df_[1:,:,:]
                    dat_seaw_dfn = dat_seaw_df_[1:,:,:]
                    ind_sean_dfn = ind_sean_df_[1:,:]
                    ind_seaw_dfn = ind_seaw_df_[1:,:]

                    for time in range(31):
                        dat_sean_dfn[:,:,time] = np.multiply((dat_sean_dfn[:,:,time]),ind_sean_dfn)
                        dat_seaw_dfn[:,:,time] = np.multiply(np.array(dat_seaw_dfn[:,:,time]),ind_seaw_dfn)

                    for speak in range(0,5):

                        dat_sean_res = dat_sean_dfn[:,speak,:]
                        dat_seaw_res = dat_seaw_dfn[:,speak,:]

                        dat_sean_res[dat_sean_res == np.inf] = 0
                        dat_seaw_res[dat_seaw_res == np.inf] = 0
                        if(np.any(dat_seaw_res == np.inf)==True or np.any(dat_sean_res == np.inf)==True or np.any(dat_sean_res == -np.inf)==True or np.any(dat_seaw_res == -np.inf)==True):
                            print(1)

                        file1 = "C:/Users/m.nedeljkovic/Desktop/cnn data/data/an" + str(br) + '_' + "sp" + str(speak) +  ".npy"
                        #file2 = "C:/Users/m.nedeljkovic/Desktop/cnn data/data/aw" + str(br) + ".npy"
                        #file1 = "C:/Users/Zephyrus/Desktop/cnn data/data/an" + str(br) + ".npy"
                        #file2 = "C:/Users/Zephyrus/Desktop/cnn data/data/aw" + str(br) + ".npy"
                    
                        np.save(file1, dat_sean_res)
                        #np.save(file2, dat_seaw_df)
                    
                    br = br + 1
        

In [122]:
mat_load, roi_load, ind_load, list1, list2, list3, list4 = load_data()
data_speak(1, mat_load, roi_load, ind_load, list1, list2, list3, list4)

C:\Users\m.nedeljkovic\AppData\Local\Temp\ipykernel_10432\1673773893.py:62: RuntimeWarning: invalid value encountered in multiply
  dat_seaw_dfn[:,:,time] = np.multiply(np.array(dat_seaw_dfn[:,:,time]),ind_seaw_dfn)
